### ISSUE TITLE
Display event time and day of week

### ISSUE THREAD

**Issue by iandunn** [Automattic/nearby-wordpress-events#26]
Suggested by @mrwweb on the make/Community feedback post:

https://make.wordpress.org/community/2017/03/23/showing-upcoming-local-events-in-wp-admin/#comment-23294

> 2. One thing I’ve learned about meetups is that time of day makes a huge difference for who is interested in attending. That’s a determining factor for many attendees. Therefore, displaying the start time feels like a worthwhile piece of information to reduce the number of clicks through to meetup.com that don’t result in an RSVP.

See the p2 comments for more discussion and details. Feedback on the idea might change the details or implementation.

**Comment by coreymckrill** [comment]
@mapk You might be interested in reviewing this one. I recall that you had a particular vision for what information to display for each event...

**Comment by mapk** [comment]
I'm not opposed to adding the time in the feed. Maybe it can be placed below the date?

But I also don't think this widget is the end-all interaction point for these meetups and WCs. In order to attend a Meetup, they still need to click on the link and mark that they are attending... along with getting the exact location as well. I think the widget is just supposed to inform the user of upcoming events nearby. For more information, clicking through to the actual post seems acceptable.
